### ISSUE TITLE
Bootstrapping is broken in ML8 EA1

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/roxy#241]
Bootstrap against ML8 EA1:

```
$ ./ml local bootstrap
Bootstrapping your project into MarkLogic on localhost...
ERROR: 500 "XDMP-AS: (err:XPTY0004) $query as xs:string -- Invalid coercion: () as xs:string"
ERROR: {"error":{"format-string":"XDMP-AS: (err:XPTY0004) $query as xs:string -- Invalid coercion: () as xs:string”}}
```

I hear from engineering that the request interface did not change, but some of the responses may have. The error above is probably from parsing the response.

**Comment by worldlynutter** [comment]
Hi.

I know Roxy is an external project.  However, in threads earlier this year on the Roxy GitHub pages, it was stated that the likely final solution for Roxy that included changes by the Engineering team. See: https://github.com/marklogic/roxy/issues/241 - specifically post of 7 June.

The question: 
Do you consider that these changes are implemented in EA3 so that I can consider Roxy 'officially' usable in MarkLogic 8 based on the current code or would you consider that all workarounds are now replaces with a final solution?

The reason: I need to give a client information related to Roxy and MarkLogic 8 and do not want to do so if the current solution for Roxy is based on workarounds and not a final solution.

I have posted a similiar question in the ML8 EA forums as well and referred to this thread.

Kind Regards,
David Ennis

**Comment by dmcassel** [comment]
I believe the current solution is the official one and that no changes from Engineering were needed. @paxtonhare can you confirm?

**Comment by grtjn** [comment]
To put it short: we found ways around, that didn't require Engineering to revert or change anything. Works fine with all ea's of ml 8, and equally well with ml 7..


Sent from Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: David Cassel <notifications@github.com> 
Datum: 04-01-2015  17:21  (GMT+01:00) 
Aan: marklogic/roxy <roxy@noreply.github.com> 
Cc: Geert <geert.josten@xs4all.nl> 
Onderwerp: Re: [roxy] Bootstrapping is broken in ML8 EA1 (#241) 
 
I believe the current solution is the official one and that no changes from Engineering were needed. @paxtonhare can you confirm?

**Comment by worldlynutter** [comment]
Thanks for the reply.  I've also updated my EA forum post with the same information.

Kind Regards,
David Ennis
