### ISSUE TITLE
Do you have more specific instructions for using the ML.txt?

### ISSUE THREAD

**Issue by stephen-gehring-ml** [marklogic-community/roxy#368]
A Question: Do you have more specific instructions for using the ML.txt?
I still struggle with shell scripts and I am not really sure where to place the ml.txt file or how to hook it up so I can run it in my command line...

**Comment by stephen-gehring-ml** [comment]
What are your thoughts about deeper diving into more in depth instructions for setting up the ml.txt...
MAC
1) changing the extension to .sh
2) make the .sh an executable
3) putting the file in a ~/bin folder
4) adding the alias to you .bash_profile
http://www.moncefbelyamani.com/create-aliases-in-bash-profile-to-assign-shortcuts-for-common-terminal-commands/

This will help open up access by making it easier for beginners to get up and running.

**Comment by grtjn** [comment]
I have a generic copy of the ml-script in a Projects folder from where I create new projects. Once I have created a project, I always use the local copy of the ml-script within the project using `./ml ...`.

Instead of downloading the ml-script from github manually, which causes browsers to typically add the unnecessary .txt extension, you could also use curl to grab it:

```
curl -o ml https://raw.githubusercontent.com/marklogic/roxy/master/ml
```

To make it executable:

```
chmod +x ml
```

Note: we normally don't add the .sh extension, just remove the .txt, and make it executable. Putting it in your PATH to run it from anywhere is optional.

Looking at the docs though (README and Wiki Home), clearer instructions would be helpful there I think. Various hints are given, but you have to look for it..

**Comment by grtjn** [comment]
This would be the best place to make an update: https://github.com/marklogic/roxy/wiki#installation

**Comment by RobertSzkutak** [comment]
I added some detail to that wiki page. Feel free to pass on any feedback if it could be further improved.
